server:
  port: 8091

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.01:3306/easymall?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    connect-timeout: 30000
#redis

#mybatis
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.hai.entity

#showsql
logging:
  level:
    com:
      hai:
      springboot_ssm:
      mapper: debug

